[phases.setup]
nixPkgs = ["nodejs", "python310", "python310Packages.pip", "python310Packages.virtualenv"]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && cd telegram_bot && pip install -r requirements.txt",
    ". /opt/venv/bin/activate && cd telegram_bot/admin_dashboard && pip install -r requirements.txt",
    "cd telegram_bot/admin_dashboard && npm install"
]

[phases.build]
cmds = [
    "cd telegram_bot/admin_dashboard && npm run build"
]

[start]
cmd = ". /opt/venv/bin/activate && cd telegram_bot/admin_dashboard && python start_server.py" 