[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "cd webapp && npm install"
]

[phases.build]
cmds = [
    "cd webapp && npm run build"
]

[start]
cmd = "cd webapp && npx serve -s dist -l $PORT" 